### ISSUE TITLE
"a java exception has occurred"

### ISSUE THREAD

**Issue by lasercar** [gildedgames/aether-issues#413]
When I click on the newest launcher, an alert comes up saying "a java exception has occurred"; nothing else happens, the launcher does not open.
OS: Windows 7 (64 bit)
Java: 7 (64-bit)

**Comment by xJonL** [comment]
Our launcher has problems on Java 7, try updating to Java 8 and see if this fixes your issue.

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by xJonL** [comment]
We've fixed our launcher issues with Java 7, feel free to update if you want still, it's not required.

**Comment by Collin1971** [comment]
Does the issue still occur when you use this file to launch? https://collin1971.net/p/mirrors/aetherii/files/launcher/bootstrapper/1.1.2/launcher-start.jar

**Comment by lasercar** [comment]
@Collin1971 Yes, that launcher file works with no issues! (still on Java 7)
