### ISSUE TITLE
Breaking Carved Stone drops Carved Stone with data value 1

### ISSUE THREAD

**Issue by ajthemacboy** [gildedgames/aether-issues#561]
Mining or breaking Carved Stone drops Carved Stone with a data value of 1. The dropped stone cannot be stacked with the normal stone. 

Is this intended behaviour? It's certainly annoying to build with.

**Comment by xJonL** [comment]
Can confirm, mobs when they are killed dropped carved stone with meta of 0, however mining the block inside of dungeons give you meta of 1.

**Comment by Latevladiator** [comment]
Happens to me as well

**Comment by Collin1971** [comment]
I've fixed this in the next upcoming release. :smile:

**Comment by MoltenLichQueen** [comment]
The bug is still present as of Aether 1.6. [Proof](https://youtu.be/AvSM9eNzIPY). Happens with Sentry Blocks as well.
