### ISSUE TITLE
Aether sword glitch

### ISSUE THREAD

**Issue by g17123** [gildedgames/aether-issues#580]
Every aether sword that I use on the official server instantly disappears. Only vanilla swords work.
Edit:Glitch only happens some times but effects everyone when it happens.

**Comment by Collin1971** [comment]
We resolved the issue on the Aether Official Server around a week ago and this issue was never closed.

Please do not create issues pertaining to the Aether Official Server on this issue tracker.

**Comment by Collin1971** [comment]
This issue still occurs according to #587.

**Comment by xJonL** [comment]
Should be fixed

**Comment by Collin1971** [comment]
_This issue still occurs on the Aether Official Server._

@xJonL: Please do not close the issue again.

**Comment by Collin1971** [comment]
This issue is not limited to swords on the Aether Official Server. We've received multiple reports, and we're watching it carefully until we're able to figure out what's going on.

**Comment by xJonL** [comment]
seems to be an issue with the server jar KCauldon will have to make an issue there, i'll get to that for you
